/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.itla.app;

/**
 *
 * @author Akme
 */
public class RegisterView extends javax.swing.JPanel {

    /**
     * Creates new form RegisterView
     */
    public RegisterView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        txt_password = new javax.swing.JPasswordField();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        txt_username = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        txt_name = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        txt_lastname = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        txt_phone = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        txt_email = new javax.swing.JTextField();
        txt_passconfirm = new javax.swing.JPasswordField();
        jSeparator5 = new javax.swing.JSeparator();
        jComboBox1 = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_password.setBackground(new java.awt.Color(255, 255, 255));
        txt_password.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txt_password.setForeground(new java.awt.Color(112, 112, 112));
        txt_password.setText("Password");
        txt_password.setBorder(null);
        txt_password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_passwordFocusLost(evt);
            }
        });
        txt_password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_passwordMouseClicked(evt);
            }
        });
        jPanel4.add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 380, -1));

        jPanel3.setBackground(new java.awt.Color(67, 194, 251));

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("REGISTER");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel4.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 150, 38));
        jPanel4.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 381, 10));

        txt_username.setBackground(new java.awt.Color(255, 255, 255));
        txt_username.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txt_username.setForeground(new java.awt.Color(112, 112, 112));
        txt_username.setText("Username");
        txt_username.setBorder(null);
        txt_username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_usernameFocusLost(evt);
            }
        });
        txt_username.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_usernameMouseClicked(evt);
            }
        });
        jPanel4.add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 380, -1));
        jPanel4.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 381, 10));

        txt_name.setBackground(new java.awt.Color(255, 255, 255));
        txt_name.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txt_name.setForeground(new java.awt.Color(112, 112, 112));
        txt_name.setText("Name");
        txt_name.setBorder(null);
        txt_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_nameFocusLost(evt);
            }
        });
        txt_name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_nameMouseClicked(evt);
            }
        });
        jPanel4.add(txt_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 380, -1));
        jPanel4.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 381, 10));
        jPanel4.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 381, 10));

        txt_lastname.setBackground(new java.awt.Color(255, 255, 255));
        txt_lastname.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txt_lastname.setForeground(new java.awt.Color(112, 112, 112));
        txt_lastname.setText("Last name");
        txt_lastname.setBorder(null);
        txt_lastname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_lastnameFocusLost(evt);
            }
        });
        txt_lastname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_lastnameMouseClicked(evt);
            }
        });
        jPanel4.add(txt_lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 380, -1));
        jPanel4.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 381, 10));

        txt_phone.setBackground(new java.awt.Color(255, 255, 255));
        txt_phone.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txt_phone.setForeground(new java.awt.Color(112, 112, 112));
        txt_phone.setText("Phone");
        txt_phone.setBorder(null);
        txt_phone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_phoneFocusLost(evt);
            }
        });
        txt_phone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_phoneMouseClicked(evt);
            }
        });
        jPanel4.add(txt_phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 380, -1));
        jPanel4.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 381, 10));

        txt_email.setBackground(new java.awt.Color(255, 255, 255));
        txt_email.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txt_email.setForeground(new java.awt.Color(112, 112, 112));
        txt_email.setText("Email");
        txt_email.setBorder(null);
        txt_email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_emailFocusLost(evt);
            }
        });
        txt_email.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_emailMouseClicked(evt);
            }
        });
        jPanel4.add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 380, -1));

        txt_passconfirm.setBackground(new java.awt.Color(255, 255, 255));
        txt_passconfirm.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txt_passconfirm.setForeground(new java.awt.Color(112, 112, 112));
        txt_passconfirm.setText("Password");
        txt_passconfirm.setBorder(null);
        txt_passconfirm.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_passconfirmFocusLost(evt);
            }
        });
        txt_passconfirm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_passconfirmMouseClicked(evt);
            }
        });
        jPanel4.add(txt_passconfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 380, -1));
        jPanel4.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 381, 10));

        jComboBox1.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Employ", "Visitor", " " }));
        jComboBox1.setBorder(null);
        jPanel4.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 120, -1));

        add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 400));
    }// </editor-fold>//GEN-END:initComponents

    private void txt_usernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_usernameMouseClicked
        txt_username.setText("");
    }//GEN-LAST:event_txt_usernameMouseClicked

    private void txt_usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_usernameFocusLost
        if(this.txt_username.getText().isEmpty())
            this.txt_username.setText("Username");
    }//GEN-LAST:event_txt_usernameFocusLost

    private void txt_nameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_nameMouseClicked
        this.txt_name.setText("");
    }//GEN-LAST:event_txt_nameMouseClicked

    private void txt_nameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_nameFocusLost
        if(this.txt_name.getText().isEmpty())
            this.txt_name.setText("Name");
    }//GEN-LAST:event_txt_nameFocusLost

    private void txt_lastnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_lastnameMouseClicked
        this.txt_lastname.setText("");
    }//GEN-LAST:event_txt_lastnameMouseClicked

    private void txt_lastnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_lastnameFocusLost
        if(this.txt_lastname.getText().isEmpty())
            this.txt_lastname.setText("Last Name");
    }//GEN-LAST:event_txt_lastnameFocusLost

    private void txt_phoneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_phoneMouseClicked
        this.txt_phone.setText("");
    }//GEN-LAST:event_txt_phoneMouseClicked

    private void txt_phoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_phoneFocusLost
        if(this.txt_phone.getText().isEmpty())
            this.txt_phone.setText("Phone");
    }//GEN-LAST:event_txt_phoneFocusLost

    private void txt_emailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_emailMouseClicked
        this.txt_email.setText("");
    }//GEN-LAST:event_txt_emailMouseClicked

    private void txt_emailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_emailFocusLost
        if(this.txt_email.getText().isEmpty())
            this.txt_email.setText("Email");
    }//GEN-LAST:event_txt_emailFocusLost

    private void txt_passwordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_passwordMouseClicked
        this.txt_password.setText("");
    }//GEN-LAST:event_txt_passwordMouseClicked

    private void txt_passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_passwordFocusLost
        if(String.valueOf(this.txt_password.getPassword()).isEmpty())
            this.txt_password.setText("Password");
    }//GEN-LAST:event_txt_passwordFocusLost

    private void txt_passconfirmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_passconfirmMouseClicked
        this.txt_passconfirm.setText("");
    }//GEN-LAST:event_txt_passconfirmMouseClicked

    private void txt_passconfirmFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_passconfirmFocusLost
        if(String.valueOf(this.txt_passconfirm.getPassword()).isEmpty())
            this.txt_passconfirm.setText("Password");
    }//GEN-LAST:event_txt_passconfirmFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_lastname;
    private javax.swing.JTextField txt_name;
    private javax.swing.JPasswordField txt_passconfirm;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_phone;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
